# Site settings
name: Autonomy and Verification Network
email:
author: Autonomy and Verification Network

keywords: autonomous systems, robotics, artificial intelligence, formal verification, sensor systems, programming, formal modelling
description: The Autonomy and Verification Network is distributed across several universities, including The University of Manchester, University of Liverpool, Liverpool John Moores University, and Lancaster University Leipzig

# Only use this if you are serving your site via Github Pages
#github:

#url:  "http://localhost:4000"
#images: "http://localhost:4000/images/"

url: "https://autonomy-and-verification.github.io"
images: "https://autonomy-and-verification.github.io/images/"


header: no
header_sm: images/ashton-small.png
header_med: images/ashton-med.png
header_large: images/ashton-large.png
header_xl: images/ashton-xl-desat.png

include: [_events]

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

collections:
  events:
    output: true
  projects:
    output: false
  projects-previous:
    output: false
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

address:
  - line: 

#Google API key
google_api_key: AIzaSyB1miEwJXVP4HydUImEL5ONmzvCL37_dBU

#### SEO Stuff

# Twitter Cards
twitter_user: LivUni_AVLab
twitter_card: true
twitter_image: https://autonomy-and-verification.github.io/images/ashton-home.png    #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Usernames for things
researchgate_username: Autonomy-and-Verification-Lab-Michael-Fisher

# URLS
UoL_URL: https://www.liverpool.ac.uk/computer-science/
UoY_URL: https://www.cs.york.ac.uk/
AA_URL: https://www.york.ac.uk/assuring-autonomy/
ONR_URL: http://www.onr.org.uk/
NCNR_HUB_URL: https://www.ncnr.org.uk/
RAIN_HUB_URL: https://rainhub.org.uk/
VV_NETWORK_URL: https://vavas.org/
